function set_x_actual()
global t t_0
global x_actual_0
global x_actual u_actual_func
global param
persistent t_prev x_actual_prev
if t==t_0
    x_actual=x_actual_0;
    x_actual_prev=x_actual_0;
    t_prev=t_0;
elseif t==t_prev
    ;
elseif t>t_prev
    %True system state is generated by integration using MATLAB ode45 integrator
    ode45_options=odeset('RelTol',1e-12,'AbsTol',1e-12);
    [time_steps,x_steps] = ode45(@(t,x_) dstate(x_, u_actual_func(t_prev), t_prev,param),[t_prev,t],x_actual_prev,ode45_options);
    x_actual=x_steps(end,:)';
    x_actual_prev=x_actual;
    t_prev=t;
else
    error('t must be such t==t_0 or t=t_prev+Delta_t');
end
end
